version: '2'

services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - MAIL_USERNAME=937371423@qq.com
      - MAIL_PASSWORD=rdyuwlebtveybfae

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web
